spring.application.name=MediConnect
spring.datasource.url=jdbc:mysql://u1652_SKB3DHr5SC:%5EtTXWf6gZ%5E48FpM6Ed%5EPz%40DA@sara.hidencloud.com:3306/s1652_ENERGYCODES?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=u1652_SKB3DHr5SC
spring.datasource.password=^tTXWf6gZ^48FpM6Ed^Pz@DA

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.sql.init.mode=never

app.jwt.secret=miClaveSecretaSuperSeguraParaMediConnect2026XYZ
app.jwt.expiration=86400000