spring.application.name=MediConnect
server.port=8083
spring.datasource.url=jdbc:mysql://u1652_SKB3DHr5SC:%5EtTXWf6gZ%5E48FpM6Ed%5EPz%40DA@sara.hidencloud.com:3306/s1652_ENERGYCODES?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=u1652_SKB3DHr5SC
spring.datasource.password=^tTXWf6gZ^48FpM6Ed^Pz@DA

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.default_schema=s1652_ENERGYCODES
spring.jpa.show-sql=true

spring.sql.init.mode=never

app.jwt.secret=miClaveSecretaSuperSeguraParaMediConnect2026XYZ
app.jwt.expiration=86400000


# Configuración de swagger y apidocs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs